config/routes.rb
Rails.application.routes.draw do
  root to: 'buyers#index', constraints: {domain: 'xiumaijia.com'}
  root to: 'pages#index'
  get 'y/(*custom)', to: 'articles#draft'

  resources :topics, only: [:index]

  resources :taobao_items, path: :items, param: :item_no, only: [:index, :show]
  resources :taobao_reviews, path: :reviews, param: :review_no, only: [:show]

  get 'asgard', to: 'asgard#index'
  namespace :asgard do
    resources :taobao_items, only: [:index, :create]
    resources :topics, only: [:index, :create]
    resources :ninety_videos, only: [:index, :create]
  end

  get 'comments/index'
  get 'login', to: 'sessions#new'
  delete 'logout', to: 'sessions#destroy'

  resources :repos do
    resources :tags
  end

  resources :tags
  resource :highlighter, only: [:show, :create]
  resources :forms
  resources :comments do
    collection do
      post :normal_create
    end
  end
  resources :sessions, only: [:create]
  resources :pictures, only: [:index, :show, :create], param: :pid
  resources :articles, only: [:index, :show, :new, :edit, :create, :update]

  get 'gif', to: 'gif#index'
  namespace :gif do
    post :metadata
  end

  namespace :pages do
    get :girls
    get :send_mail
    get :exception
    get :vertical_center
    get :bilibili_gifs
    get :bilibili_random
    get :gallery
    get :web_socket
    get :chat
    get :hupu_news_list
    get :path_diff
    get :time_zone
    get :navigation
    get :background
    get :ordered_load
    get :ordered_load_logos
    get :bind
    get :dns
    get :swipe
  end

  namespace :demos do
    get :material
    get :show, to: redirect('https://www.xiumaijia.com', status: 301)
  end

  namespace :d do
    resources :authors, only: [:index, :create, :update]
    resources :nba_games, only: [:index]
    resources :nba_images, only: [] do
      collection do
        get :random
      end
    end

    resources :photos, only: [] do
      collection do
        get :random
      end
    end

    resources :bilibili_gifs, only: [:index] do
      collection do
        get :random
      end
    end

    resources :ninety, only: [] do
      collection do
        get :fetch
      end
    end
  end

  mount EchoServer.new, at: '/ws/echo_server', as: :echo_server
  mount BroadcastServer.new, at: '/ws/broadcast_server', as: :broadcast_server

  mount LetsencryptPlugin::Engine, at: '/'  # It must be at root level

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web, at: '/sidekiq'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/tag.rb
require 'net/http'
require 'git_repo_parser'
require 'highlight'

class Tag < ApplicationRecord

  ## Associations
  belongs_to :repo

  ## Validations
  validates :repo, presence: true
  validates :name, presence: true, length: {maximum: 100}
  validates :git_url, presence: true, length: {maximum: 250}
  validates :git_commit, presence: true, length: {is: 40}

  def dockerfile_url
    GitRepoParser.dockerfile_url(git_url, git_commit, dockerfile_dir)
  end

  # download dockerfile and record download time
  # @return [TrueClass]
  # @return [FalseClass]
  def download_dockerfile
    content = Net::HTTP.get(URI(self.dockerfile_url))
    self.update(
      {
        dockerfile_content: content.force_encoding('utf-8'),
        dockerfile_downloaded_at: DateTime.now,
      }
    )
  end

  def buildable_url
    GitRepoParser.buildable_url(git_url, git_commit, dockerfile_dir)
  end

  # @return [String]
  # @return [NilClass]
  def highlighted_content
    if dockerfile_content.present?
      lexer = Rouge::Lexers::Dockerfile.new
      formatter = Rouge::Formatters::HTML.new
      formatter.format(lexer.lex(dockerfile_content))
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_action :set_repo, only: [:index, :new, :create]
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    if @repo.present?
      @tags = @repo.tags
    else
      @tags = Tag.all
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    if @tag.dockerfile_content.blank?
      @tag.download_dockerfile
    end
  end

  # GET /tags/new
  def new
    @tag = @repo.tags.build
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = @repo.tags.build(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :git_url, :git_commit, :dockerfile_dir)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.slim
= form_for @tag do |f|
  - if @tag.errors.any?
    #error_explanation
      h2 = "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
      ul
        - @tag.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :repo
    = f.text_field :repo
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :git_url
    = f.text_field :git_url
  .field
    = f.label :git_commit
    = f.text_field :git_commit
  .field
    = f.label :dockerfile_dir
    = f.text_field :dockerfile_dir
  .actions = f.submit

app/views/tags/edit.html.slim
h1 Editing tag

== render 'form'

= link_to 'Show', @tag
'|
= link_to 'Back', tags_path

app/views/tags/index.html.slim
h1 Listing tags

table
  thead
    tr
      th Repo
      th Name
      /th Git url
      /th Git commit
      /th Dockerfile dir
      /th Dockerfile url
      th
      th
      th

  tbody
    - @tags.each do |tag|
      tr
        td = tag.repo
        td = tag.name
        /td = tag.git_url
        /td = tag.git_commit
        /td = tag.dockerfile_dir
        /td = link_to tag.dockerfile_url, tag.dockerfile_url, target: '_blank'
        td = link_to 'Show', tag
        td = link_to 'Edit', edit_tag_path(tag)
        td = link_to 'Destroy', tag, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Tag', new_tag_path

app/views/tags/new.html.slim
h1 New tag

== render 'form'

= link_to 'Back', tags_path

app/views/tags/show.html.slim
p#notice = notice

p
  strong Repo:
  = @tag.repo
p
  strong Name:
  = @tag.name
p
  strong Git url:
  = @tag.git_url
p
  strong Git commit:
  = @tag.git_commit
p
  strong Dockerfile dir:
  = @tag.dockerfile_dir
div
  strong Dockerfile url:
  div = link_to @tag.dockerfile_url, @tag.dockerfile_url, target: '_blank'
p
  strong Dockerfile downloaded at:
  = @tag.dockerfile_downloaded_at

div
  strong Buildable url:
  div = @tag.buildable_url

div
  strong Dockerfile content:
  = sanitize @tag.highlighted_content

= link_to 'Edit', edit_tag_path(@tag)
'|
= link_to 'Back', tags_path